version: "2.2"

services: 
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - graph_network

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - graph_network
  
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_vol:/var/lib/grafana

    ports:
    - "3000:3000"
    networks:
    - graph_network

  statsd:
   image: graphiteapp/graphite-statsd
   ports:
    - "81:80"
    - "2003-2004:2003-2004"
    - "2023-2024:2023-2024"
    - "8125:8125/udp"
    - "8126:8126"
   networks:
    - graph_network
   volumes:
    - graphite_vol:/var/lib/graphite
    - ./conf/opt/graphite/conf/:/opt/graphite/conf/


volumes:
  grafana_vol:
    driver: local
  influxdb-data:
    driver: local
  graphite_vol:
    driver: local

networks:
  graph_network:
    driver: bridge
